# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        pg: [17, 16, 15, 14, 13]
    name: 🐘 PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
    - uses: actions/checkout@v4
    - name: Install GSSAPI development headers
      run: |
        sudo apt-get update
        sudo apt-get install libkrb5-dev
    - name: Start PostgreSQL
      run: pg-start ${{ matrix.pg }}
    - name: Run tests
      run: pg-build-test
